# Generated by Django 6.0 on 2026-02-09 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="finder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finder_conversations",
                to="user.user",
                verbose_name="拾主",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_conversations",
                to="user.user",
                verbose_name="失主",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
                verbose_name="发送者",
            ),
        ),
    ]
