# Generated by Django 6.0 on 2026-03-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="备份名称")),
                (
                    "backup_type",
                    models.CharField(
                        choices=[("full", "全量备份"), ("incremental", "增量备份")],
                        default="full",
                        max_length=20,
                        verbose_name="备份类型",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="文件路径"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
                ("tables", models.JSONField(default=list, verbose_name="包含的表")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("processing", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("created_by", models.BigIntegerField(verbose_name="创建人ID")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "备份记录",
                "verbose_name_plural": "备份记录",
                "db_table": "backup_record",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="ExportTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="任务名称")),
                ("data_types", models.JSONField(default=list, verbose_name="数据类型")),
                (
                    "export_format",
                    models.CharField(
                        choices=[("excel", "Excel"), ("csv", "CSV"), ("json", "JSON")],
                        default="excel",
                        max_length=20,
                        verbose_name="导出格式",
                    ),
                ),
                (
                    "date_range_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始日期"
                    ),
                ),
                (
                    "date_range_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束日期"
                    ),
                ),
                (
                    "include_images",
                    models.BooleanField(default=False, verbose_name="包含图片"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="文件路径"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
                ("record_count", models.IntegerField(default=0, verbose_name="记录数")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("processing", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度(%)")),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("created_by", models.BigIntegerField(verbose_name="创建人ID")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "导出任务",
                "verbose_name_plural": "导出任务",
                "db_table": "export_task",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("backup", "数据备份"),
                            ("restore", "数据恢复"),
                            ("export", "数据导出"),
                            ("cleanup", "数据清理"),
                        ],
                        max_length=50,
                        verbose_name="操作类型",
                    ),
                ),
                ("operation_detail", models.TextField(verbose_name="操作详情")),
                ("ip_address", models.CharField(max_length=50, verbose_name="IP地址")),
                ("user_id", models.BigIntegerField(verbose_name="用户ID")),
                ("user_name", models.CharField(max_length=100, verbose_name="用户名")),
                (
                    "operation_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "db_table": "system_operation_log",
                "ordering": ["-operation_time"],
            },
        ),
    ]
