# Generated by Django 6.0 on 2026-03-07 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("technical", "技术问题"),
                            ("usage", "使用问题"),
                            ("suggestion", "意见建议"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="问题类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="反馈内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("resolved", "已解决"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "reply",
                    models.TextField(blank=True, null=True, verbose_name="管理员回复"),
                ),
                (
                    "reply_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="回复时间"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="user.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户反馈",
                "verbose_name_plural": "用户反馈",
                "db_table": "feedback",
                "ordering": ["-create_time"],
            },
        ),
    ]
