# Generated by Django 6.0.1 on 2026-01-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(verbose_name="发布人ID")),
                ("item_type", models.SmallIntegerField(verbose_name="物品类型ID")),
                ("item_category", models.SmallIntegerField(verbose_name="信息类型")),
                ("name", models.CharField(max_length=50, verbose_name="物品名称")),
                ("location_id", models.BigIntegerField(verbose_name="地点ID")),
                ("happen_time", models.DateTimeField(verbose_name="发生时间")),
                ("feature", models.TextField(verbose_name="物品特征描述")),
                (
                    "reward_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="悬赏金额",
                    ),
                ),
                (
                    "reward_desc",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="悬赏说明"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=20, verbose_name="联系人姓名"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=11, verbose_name="联系人电话"),
                ),
                ("current_status", models.SmallIntegerField(verbose_name="当前状态")),
                (
                    "reject_reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="驳回原因"
                    ),
                ),
                (
                    "archive_desc",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="归档说明"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "audit_user_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="审核人ID"
                    ),
                ),
                (
                    "audit_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "物品信息",
                "verbose_name_plural": "物品信息",
                "db_table": "item",
            },
        ),
    ]
