# Generated by Django 6.0.1 on 2026-01-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                ("parent_id", models.BigIntegerField(verbose_name="父分类ID")),
                ("sort", models.SmallIntegerField(verbose_name="排序")),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.BigIntegerField(verbose_name="物品ID")),
                ("claim_user_id", models.BigIntegerField(verbose_name="认领人ID")),
                ("proof_feature", models.TextField(verbose_name="证明特征")),
                ("status", models.SmallIntegerField(verbose_name="状态")),
                (
                    "reject_reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="驳回原因"
                    ),
                ),
                (
                    "audit_user_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="审核人ID"
                    ),
                ),
                (
                    "audit_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "claim_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="认领时间"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "认领申请",
                "verbose_name_plural": "认领申请",
                "db_table": "claim",
            },
        ),
        migrations.CreateModel(
            name="ItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.BigIntegerField(verbose_name="物品ID")),
                (
                    "image_url",
                    models.CharField(max_length=255, verbose_name="图片地址"),
                ),
                ("image_type", models.SmallIntegerField(verbose_name="图片类型")),
                ("sort", models.SmallIntegerField(verbose_name="排序")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "物品图片",
                "verbose_name_plural": "物品图片",
                "db_table": "item_image",
            },
        ),
        migrations.CreateModel(
            name="ItemStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.BigIntegerField(verbose_name="物品ID")),
                ("old_status", models.SmallIntegerField(verbose_name="原状态")),
                ("new_status", models.SmallIntegerField(verbose_name="新状态")),
                ("operator_id", models.BigIntegerField(verbose_name="操作人ID")),
                ("operator_type", models.SmallIntegerField(verbose_name="操作人类型")),
                (
                    "operate_reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="操作原因"
                    ),
                ),
                (
                    "operate_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
            ],
            options={
                "verbose_name": "物品状态历史",
                "verbose_name_plural": "物品状态历史",
                "db_table": "item_status_history",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="地点名称")),
                ("parent_id", models.BigIntegerField(verbose_name="父地点ID")),
                ("sort", models.SmallIntegerField(verbose_name="排序")),
                ("status", models.SmallIntegerField(default=1, verbose_name="状态")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "地点",
                "verbose_name_plural": "地点",
                "db_table": "location",
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="公告标题")),
                ("content", models.TextField(verbose_name="公告内容")),
                (
                    "priority",
                    models.SmallIntegerField(default=2, verbose_name="优先级"),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("status", models.SmallIntegerField(verbose_name="状态")),
                ("create_user_id", models.BigIntegerField(verbose_name="创建人ID")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告",
                "db_table": "notice",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(verbose_name="用户ID")),
                ("title", models.CharField(max_length=100, verbose_name="通知标题")),
                ("content", models.TextField(verbose_name="通知内容")),
                ("type", models.SmallIntegerField(verbose_name="通知类型")),
                (
                    "is_read",
                    models.SmallIntegerField(default=0, verbose_name="是否已读"),
                ),
                (
                    "related_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="关联ID"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "read_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="阅读时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "站内通知",
                "verbose_name_plural": "站内通知",
                "db_table": "notification",
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(verbose_name="用户ID")),
                ("user_role", models.SmallIntegerField(verbose_name="用户角色")),
                ("module", models.CharField(max_length=50, verbose_name="操作模块")),
                ("operation", models.CharField(max_length=50, verbose_name="操作名称")),
                (
                    "related_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="关联ID"
                    ),
                ),
                ("content", models.TextField(verbose_name="操作内容")),
                ("ip_address", models.CharField(max_length=50, verbose_name="IP地址")),
                (
                    "operation_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "db_table": "operation_log",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=20, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=100, verbose_name="密码哈希")),
                ("real_name", models.CharField(max_length=20, verbose_name="真实姓名")),
                (
                    "phone",
                    models.CharField(max_length=11, unique=True, verbose_name="手机号"),
                ),
                ("role", models.SmallIntegerField(verbose_name="角色")),
                (
                    "status",
                    models.SmallIntegerField(default=1, verbose_name="账号状态"),
                ),
                (
                    "first_login",
                    models.SmallIntegerField(default=1, verbose_name="是否首次登录"),
                ),
                (
                    "last_login_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后登录时间"
                    ),
                ),
                (
                    "last_login_ip",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="最后登录IP"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "user",
            },
        ),
    ]
