# Generated by Django 6.0.1 on 2026-01-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_category_claim_itemimage_itemstatushistory_location_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
