# Generated by Django 6.0 on 2026-02-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="location_detail",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="具体地点描述"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.BigIntegerField(verbose_name="物品类型ID"),
        ),
    ]
