# Generated by Django 6.0 on 2026-02-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_item_location_detail_alter_item_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemimage",
            name="image_data",
            field=models.BinaryField(default=b"", verbose_name="图片二进制数据"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="image_type",
            field=models.SmallIntegerField(verbose_name="图片类型：1-失物，2-招领"),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="image_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="原始文件名"
            ),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="sort",
            field=models.SmallIntegerField(verbose_name="图片排序"),
        ),
    ]
