# Generated by Django 6.0 on 2026-02-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_itemimage_image_data_alter_itemimage_create_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="pickup_location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="领取地点"
            ),
        ),
    ]
