# Generated by Django 6.0 on 2026-02-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_item_pickup_location"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notice",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
