# Generated by Django 6.0 on 2026-02-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="公告标题")),
                ("content", models.TextField(verbose_name="公告内容")),
                (
                    "priority",
                    models.SmallIntegerField(default=2, verbose_name="优先级"),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("status", models.SmallIntegerField(verbose_name="状态")),
                ("create_user_id", models.BigIntegerField(verbose_name="创建人ID")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告",
                "db_table": "notice",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(verbose_name="用户ID")),
                ("title", models.CharField(max_length=100, verbose_name="通知标题")),
                ("content", models.TextField(verbose_name="通知内容")),
                ("type", models.SmallIntegerField(verbose_name="通知类型")),
                (
                    "is_read",
                    models.SmallIntegerField(default=0, verbose_name="是否已读"),
                ),
                (
                    "related_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="关联ID"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "read_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="阅读时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "站内通知",
                "verbose_name_plural": "站内通知",
                "db_table": "notification",
            },
        ),
    ]
